backend:
  name: github
  repo: HisyamMahfuDz/Galeri-Cosplay
  branch: main
  auth_type: implicit
  app_id: 9f7c18042c4f4d92e550  # ← ini contoh, ganti sesuai app_id kamu

media_folder: "images"
public_folder: "/images"

collections:
  - name: "galeri"
    label: "Galeri Foto"
    folder: "images"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Gambar", name: "gambar", widget: "image" }
      - { label: "Caption", name: "caption", widget: "string" }
      - { label: "Tanggal", name: "tanggal", widget: "datetime" }
